platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
project 'iDailyProject.xcodeproj'
use_frameworks!
def testing_pods
    pod 'Nimble'
end

def common_pods
  pod 'NVActivityIndicatorView', '~> 4.4.0', :inhibit_warnings => true
end

target 'iDailyProject' do
    common_pods
    testing_pods
end
